### ISSUE TITLE
Are we're there yet?

### ISSUE THREAD

**Issue by gtr3qq** [Kagamiin/ESFMu#1]
just asking.
I heard the ESFM back in the days, never be able to forget it ever since.
In case confused, I've been told that the emu is not complete yet, and only when it is complete, can the Furnace tracker team consider adding support for it.

**Comment by Kagamiin** [comment]
Hello. Nice to hear that people are interested. Sorry for the long delay. Development had been halted due to lack of personal motivation, but has recently been resumed.

@gtr3qq The emulator is currently in the testing phase. Currently, "emulation mode" (OPL3 compatibility mode) is being implemented and bugs are being fixed.

I'm currently testing in a custom build of DOSBox-X. I've been focusing on getting "emulation mode" working solidly so far, since it's easier to test with the available software and music modules, and relies solidly on native ESFM mode to work. Once that's working, I'll try to focus on getting native ESFM mode to work on Windows 95 using actual ESS drivers, which I hope work with DOSBox-X's limited ESS implementation - if not, I'll need further help with testing native mode.

I'd gladly accept any sort of help I can get with testing the emulator. I could also help with early integration of ESFMu into Furnace, as well as integrating import support for the patch formats for the ESFM bank editor we've already been using in Windows 95, if that turns out to be the most viable alternative for testing out native mode.

**Comment by Kagamiin** [comment]
By the way, should you want to keep up with my dev logs or contribute directly to ESFM reverse engineering in some way, you can join our Discord at: <https://discord.gg/qCWKyNzDU> _(note: link expires in 30 days)_
