### ISSUE TITLE
help with binaries...

### ISSUE THREAD

**Issue by d-sphinx** [Kagamiin/ESFMu#11]
Can anyone provide a link or at least some clues on getting binaries? Maybe YouTube videos with a working instance?

**Comment by Kagamiin** [comment]
Hello @d-sphinx. This is an emulation core, not a standalone application - as such, it needs to be linked into a host application in order to function.

The easiest way to use ESFMu right now, and what we've been using to test and troubleshoot stuff, is Furnace Tracker. I recommend getting LTVA1's fork, as the official version still doesn't have ESFM support implemented yet. You can check out the project page [here](https://github.com/LTVA1/furnace), and binaries are available [here](https://nightly.link/ltva1/furnace/workflows/build/master). The project also has a [Discord server](https://discord.gg/sT8zcsyJZt) in case you want to discuss something or have any questions.

Another option would be to use DOSBox-X. It doesn't yet have ESFM support, but I've been working on a patch to implement that into it (I had paused that to work on ESFM in Furnace Tracker instead, though, since that was more important for doing emulation accuracy tests). I can't say when I'll be finishing the patch, but it should be soon-ish. At some point. Unfortunately I couldn't get Windows support to work yet, only DOS.

**Comment by Kagamiin** [comment]
Oh, yeah, I almost forgot!

You can also use ESFMu in this webapp, which is a port of essplaymid to WebMIDI using ESFMu and Emscripten: <https://www.codingchords.com/junk/webmidi/esfm-web/>

It doesn't run the greatest, but it does work. You'll need some app that can connect to WebMIDI, or a MIDI device, though. Here's a demo video (sorry, my PC struggles to run it, hence the poor audio quality and crackling):


https://github.com/Kagamiin/ESFMu/assets/102362203/92de49d6-3944-4739-a0e7-d927a88f4284
